AnimalShelter/Models/Animal.cs
namespace AnimalShelter.Models
{
  public class Animal
  {
    public int AnimalId { get; set; }
    public string Name { get; set; }

    public string Url {get;set;}


    //String => Cast as DATETIME mysql
    public string Date { get; set; }
  
    // public Animal(string name, string date)
    // {
    // Animal_Id = Animal_Id;
    // Name = name;
    // Date = date;

    // }
    
    // public Animal(string date)
    // {
    // Animal_Id = Animal_Id;
    
    // Date = date;

    // }
  }
}

AnimalShelter/Models/AnimalShelterContext.cs
using Microsoft.EntityFrameworkCore;

namespace AnimalShelter.Models
{
  public class AnimalShelterContext : DbContext
  {

    public DbSet<Animal> Animals { get; set; }


    public AnimalShelterContext(DbContextOptions options) : base(options) { }
  }
}

AnimalShelter/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Collections.Generic;
using AnimalShelter.Models;


namespace AnimalShelter.Controllers
{
  public class AnimalsController : Controller
  {
    private readonly AnimalShelterContext _db;
    public AnimalsController(AnimalShelterContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Animal> model = _db.Animals.ToList();
      return View(model);
    }

      public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
      public ActionResult Create(Animal animal)
    {
      _db.Animals.Add(animal);
      
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Animal thisAnimal = _db.Animals.FirstOrDefault(animal => animal.AnimalId == id);
      return View(thisAnimal);
    }
  }
}

AnimalShelter/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnimalShelter.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

AnimalShelter/Views/Animals/Create.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h4> Add a new Animal</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  @Html.LabelFor(model => model.Date)
  @Html.TextBoxFor(model => model.Date)
   @Html.LabelFor(model => model.Url)
  @Html.TextBoxFor(model => model.Url)
  <input type = "submit" value="Add a new animal" />
}
<p>@Html.ActionLink("Show all animals", "Index")</p>

AnimalShelter/Views/Animals/Details.cshtml
@{
  Layout = "_Layout";
}

@model AnimalShelter.Models.Animal

<h2>Animal Details</h2>
<hr/>
<h3> @Html.DisplayNameFor(model => model.Name) : @Html.DisplayFor(model => model.Name)</h3>
<h3> @Html.DisplayNameFor(model => model.Date) : @Html.DisplayFor(model => model.Date)</h3>
<h3> @Html.DisplayNameFor(model => model.AnimalId) : @Html.DisplayFor(model => model.AnimalId)</h3>

<img src=@Model.Url width="250"/>

@* <img> @Html.DisplayFor(model => model.Url)</>

<p>@Html.ActionLink("Show dog", $"{@Model.Url}")</p> *@


<p>@Html.ActionLink("Back to list", "Index")</p>

AnimalShelter/Views/Animals/Index.cshtml
@{
  Layout = "_Layout";
}

@using AnimalShelter.Models;

<h1>Animals</h1>

@if (@Model.Count == 0)
{
  <h3>No animnals are here!!! woof! have been added yet!</h3>
} 

@foreach (Animal animal in Model)
{
  <li>@Html.ActionLink($"{animal.Name}", "Details", new{ id = animal.AnimalId})</li>;
}
<h3>@Html.ActionLink("Home", "Index", "Home")</h3>

AnimalShelter/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Animal Shelter</h1>
<h3><a href='/animals'>Show Animals</a></h3>
@* <h3><a href='/animals/create'>Add </a></h3> *@
<h3>@Html.ActionLink("Add animal", "Create", "Animals")</h3>

AnimalShelter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Animal Shelter!</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>